### ISSUE TITLE
Most files when passed throw this error

### ISSUE THREAD

**Issue by monishrnath** [multivac61/pv#1]
pv.py:84: RuntimeWarning: invalid value encountered in divide
  Freq0 = B/A * abs(B/A)
Traceback (most recent call last):
  File "pv.py", line 203, in <module>
    y = pv.timestretch(x, alpha)
  File "pv.py", line 127, in timestretch
    y[pp:pp+N] += w*np.fft.ifft(Y)
ValueError: operands could not be broadcast together with shapes (968,) (1024,) (968,)

**Comment by locua** [comment]
`Traceback (most recent call last):                                                                                             
  File "pv.py", line 199, in <module>                                                                                          
    y = pv.timestretch(x, alpha)                                                                                               
  File "pv.py", line 123, in timestretch                                                                                                 
    y[pp:pp+N] += w*np.fft.ifft(Y)                                                                                                       
TypeError: Cannot cast ufunc add output from dtype('complex128') to dtype('float64') with casting rule 'same_kind'      `

I get this similar error.
